sonobuoy-config:
  driver: Job
  plugin-name: custom-e2e
  result-format: manual
  source_url: https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/main/examples/e2e-skeleton/plugin.yaml
  description: An easy to start from project for making K8s aware tests.
spec:
  command:
  - bash
  args:
  - -c
  - /kube/kubectl-mtb_linux_amd64 run benchmarks -n "test" --as "system:serviceaccount:default:divya";
    mkdir -p /tmp/sonobuoy/results;
    cp /tmp/mtlb.json /tmp/sonobuoy/results/;
    tar czvf /tmp/sonobuoy/results/results.tar.gz -C /tmp/sonobuoy/results/ .;
    echo -n /tmp/sonobuoy/results/results.tar.gz > /tmp/sonobuoy/results/done
  image: mtb
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results

