kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-eng
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: 'eng.tree.hnc.x-k8s.io/depth'
          operator: Exists
