# This file can be applied to a cluster with HNC v0.5 deployment to create
# hierarchyconfiguration and subnamespaceanchor CRs. We can apply it before
# deploying v0.6 to test CRD conversion from v1alpha1 to v1alpha2.
apiVersion: v1
kind: Namespace
metadata:
  name: a
---
apiVersion: hnc.x-k8s.io/v1alpha1
kind: SubnamespaceAnchor
metadata:
  name: b
  namespace: a
